---
name: Data-ID-Maildir
version: 0.002
author:
  - 'Andrew Main (Zefram) <zefram@fysh.org>'
abstract: generate maildir-style unique IDs
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Exporter: 0
  Sys::Hostname: 0
  Time::HiRes: 1.00
  base: 0
  perl: 5.006
  strict: 0
  warnings: 0
build_requires:
  Module::Build: 0
  Test::More: 0
  perl: 5.006
  strict: 0
  warnings: 0
dynamic_config: 0
provides:
  Data::ID::Maildir:
    file: lib/Data/ID/Maildir.pm
    version: 0.002
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
distribution_type: module
